In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [2]:
df = pd.read_csv("car-details.csv")
df.sample(5)

,name,company,model,edition,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
6591,Maruti Wagon R LX BSIII,Maruti,Wagon,R LX BSIII,2007,Second,Petrol,Individual,Manual,80000,40.66,1061.0,64.0,84.33719,5.0,100000
6448,Tata Indica Vista Aqua 1.4 TDI,Tata,Indica,Vista Aqua 1.4 TDI,2010,First,Diesel,Individual,Manual,110000,39.94,1405.0,71.0,135.00000,5.0,200000
5326,Maruti Swift VDI BSIV,Maruti,Swift,VDI BSIV,2015,First,Diesel,Individual,Manual,50000,59.22,1248.0,74.0,190.00000,5.0,635000
4297,Maruti Swift Dzire ZDI,Maruti,Swift,Dzire ZDI,2013,First,Diesel,Individual,Manual,240000,55.00,1248.0,74.0,190.00000,5.0,550000
1921,Hyundai Santro GS zipDrive - Euro I,Hyundai,Santro,GS zipDrive - Euro I,2002,Fourth & Above,Petrol,Individual,Manual,120000,NaN,NaN,NaN,NaN,NaN,100000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6926 entries, 0 to 6925
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   object
 1   company        6926 non-null   object
 2   model          6926 non-null   object
 3   edition        6926 non-null   object
 4   year           6926 non-null   int64
 5   owner          6926 non-null   object
 6   fuel           6926 non-null   object
 7   seller_type    6926 non-null   object
 8   transmission   6926 non-null   object
 9   km_driven      6926 non-null   int64
 10  mileage_mpg    6718 non-null   float64
 11  engine_cc      6718 non-null   float64
 12  max_power_bhp  6717 non-null   float64
 13  torque_nm      6717 non-null   float64
 14  seats          6718 non-null   float64
 15  selling_price  6926 non-null   int64
dtypes: float64(5), int64(3), object(8)
memory usage: 865.9+ KB

In [4]:
df.isna().sum()

name               0
company            0
model              0
edition            0
year               0
owner              0
fuel               0
seller_type        0
transmission       0
km_driven          0
mileage_mpg      208
engine_cc        208
max_power_bhp    209
torque_nm        209
seats            208
selling_price      0
dtype: int64

In [5]:
df.shape

(6926, 16)

In [11]:
for col in df.select_dtypes(include="object").columns:
    print(f'Column: {col}')
    print(f'Cardinality: {df[col].nunique()}')
    print(df[col].unique())
    print()

Column: name
Cardinality: 2058
['Maruti Swift Dzire VDI' 'Skoda Rapid 1.5 TDI Ambition'
 'Honda City 2017-2020 EXi' ... 'Tata Nexon 1.5 Revotorq XT'
 'Ford Freestyle Titanium Plus Diesel BSIV'
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']

Column: company
Cardinality: 32
['Maruti' 'Skoda' 'Honda' 'Hyundai' 'Toyota' 'Ford' 'Renault' 'Mahindra'
 'Tata' 'Chevrolet' 'Fiat' 'Datsun' 'Jeep' 'Mercedes-Benz' 'Mitsubishi'
 'Audi' 'Volkswagen' 'BMW' 'Nissan' 'Lexus' 'Jaguar' 'Land' 'MG' 'Volvo'
 'Daewoo' 'Kia' 'Force' 'Ambassador' 'Ashok' 'Isuzu' 'Opel' 'Peugeot']

Column: model
Cardinality: 207
['Swift' 'Rapid' 'City' 'i20' 'Xcent' 'Wagon' '800' 'Etios' 'Figo'
 'Duster' 'Zen' 'KUV' 'Ertiga' 'Alto' 'Verito' 'WR-V' 'SX4' 'Tigor'
 'Baleno' 'Enjoy' 'Omni' 'Vitara' 'Palio' 'Verna' 'GO' 'Safari' 'Compass'
 'Fortuner' 'Innova' 'B' 'Amaze' 'Pajero' 'Ciaz' 'Jazz' 'A6' 'Corolla'
 'New' 'Manza' 'i10' 'Ameo' 'Indica' 'Vento' 'EcoSport' 'X1' 'Celerio'
 'Polo' 'Eeco' 'Scorpio' 'Freestyle' 'Passat' 'XUV500' 'Indigo' 'Terrano'
 'Creta' 'KWID' 'Santro' 'Q5' 'ES' 'XF' 'Wrangler' 'Rover' 'S-Class' '5'
 'X4' 'Superb' 'E-Class' 'Hector' 'XC40' 'Q7' 'Elantra' 'XE' 'Nexon' 'CLA'
 'Glanza' '3' 'Camry' 'XC90' 'Ritz' 'Grand' 'Matiz' 'Zest' 'Getz' 'Elite'
 'Brio' 'Hexa' 'Sunny' 'Micra' 'Ssangyong' 'Quanto' 'Accent' 'Ignis'
 'Marazzo' 'Tiago' 'Thar' 'Sumo' 'Bolero' 'GL-Class' 'Beat' 'Willys'
 'A-Star' 'XUV300' 'Nano' 'GTI' 'V40' 'CR-V' 'EON' 'RediGO' 'Captiva'
 'Fiesta' 'Seltos' 'Civic' 'Sail' 'Venture' 'Estilo' 'Classic' 'BR-V'
 'Ecosport' 'Aria' 'TUV' 'Bolt' 'Accord' 'Xylo' 'Grande' 'S-Cross' 'Yaris'
 'Tavera' 'Linea' 'Endeavour' 'Aveo' 'Esteem' 'Triber' 'Fusion' 'Octavia'
 'A4' 'XL6' 'Santa' 'Spark' 'Aspire' 'Punto' 'Optra' 'Mobilio' 'Qualis'
 'BRV' 'X6' 'Cruze' 'GLA' '6' 'NuvoSport' 'Scala' 'Jeep' 'Lodgy' 'Pulse'
 'Supro' 'Ingenio' 'Sonata' 'Renault' 'Kicks' 'Jetta' 'M-Class' 'Teana'
 'Yeti' 'Q3' 'Gurkha' 'Logan' 'A3' 'Dzire' 'Ikon' 'Fluence' 'Xenon' 'One'
 '7' 'S60' 'Lancer' 'X7' 'Premio' 'Fabia' 'Platinum' 'Captur' 'Gypsy'
 'Estate' 'Koleos' 'CLASSIC' 'Harrier' 'Multivan' 'Avventura' 'Laura'
 'Leyland' 'MUX' 'Astra' 'Tucson' 'Winger' 'Spacio' 'Venue' 'CrossPolo'
 'Marshal' 'Kodiaq' 'D-Max' 'X3' 'Land' 'X5' '309' 'Trailblazer' 'MU'
 'GLC' 'XC60' 'S90' 'S-Presso']

Column: edition
Cardinality: 1916
['Dzire VDI' '1.5 TDI Ambition' '2017-2020 EXi' ... '1.5 Revotorq XT'
 'Titanium Plus Diesel BSIV' '2.5 GX (Diesel) 8 Seater BS IV']

Column: owner
Cardinality: 5
['First' 'Second' 'Third' 'Fourth & Above' 'Test Drive Car']

Column: fuel
Cardinality: 4
['Diesel' 'Petrol' 'LPG' 'CNG']

Column: seller_type
Cardinality: 3
['Individual' 'Dealer' 'Trustmark Dealer']

Column: transmission
Cardinality: 2
['Manual' 'Automatic']

In [12]:
df = df.drop(columns=['name', 'model', 'edition'])
df.head()

,company,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000

In [14]:
df.duplicated().sum()

19

In [16]:
df = df.drop_duplicates()
df.head()

,company,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000

In [17]:
df.duplicated().sum()

0

In [20]:
X = df.drop(columns='selling_price')
y = df.selling_price.copy()

print(X.shape, y.shape)

(6907, 12) (6907,)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(5525, 12) (5525,)
(1382, 12) (1382,)

In [ ]:
num_cols = X_train.select_dtypes(include='number').columns.tolist()

['year',
 'km_driven',
 'mileage_mpg',
 'engine_cc',
 'max_power_bhp',
 'torque_nm',
 'seats']